### ISSUE TITLE
Symfony 1. Autoloader.

### ISSUE THREAD

**Issue by ruslan-polutsygan** [theodo/TheodoEvolutionLegacyWrapperBundle#18]
Hello,

Having troubles with autoloading symfony 1 project.
Seems that I have to define such dummy autoloader class:
```php
class Symfony14ClassLoader implements LegacyClassLoaderInterface
{
    /**
     * {@inheritdoc}
     */
    public function autoload()
    {
    }

    /**
     * {@inheritdoc}
     */
    public function isAutoloaded()
    {
        return true;
    }

    /**
     * {@inheritdoc}
     */
    public function setKernel(LegacyKernelInterface $kernel)
    {
    }
}
```
And set it in config then
```yaml
theodo_evolution_legacy_wrapper:
    root_dir: %kernel.root_dir%/../legacy
    class_loader_id: my_legacy_wrapper.autoload.symfony14_class_loader
```
Otherwise `Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException` is thrown - `The service "theodo_evolution_legacy_wrapper.legacy_kernel" has a dependency on a non-existent service "theodo_evolution_legacy_wrapper.autoload.class_loader".`

Isn't this better to have such class "loader" in the bundle?

Thanks
